FROM ruby:3.2.2-slim as builder

ENV RAILS_ENV=production \
    SECRET_KEY_BASE=dummy

WORKDIR /app

RUN apt-get update && \
    apt-get -y install libpq-dev curl git libicu-dev build-essential openssl && \
    curl https://deb.nodesource.com/setup_18.x | bash && \
    apt-get install -y nodejs  && \
    npm install --global yarn && \
    gem install bundler:2.5.22

COPY Gemfile* ./
RUN bundle install -j"$(nproc)"

COPY package* ./
COPY packages packages
RUN npm install

COPY . .

RUN bundle exec rails shakapacker:compile

RUN rm -rf node_modules tmp/cache vendor/bundle spec \
    && rm -rf /usr/local/bundle/cache/*.gem \
    && find /usr/local/bundle/gems/ -name "*.c" -delete \
    && find /usr/local/bundle/gems/ -name "*.o" -delete \
    && find /usr/local/bundle/gems/ -type d -name "spec" -prune -exec rm -rf {} \; \
    && rm -rf log/*.log

# Generate self-signed certificate
RUN mkdir certificate-https-local && \
    openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 \
    -subj "/C=FR/ST=France/L=Paris/O=decidim/CN=decidim.eu" \
    -keyout ./certificate-https-local/key.pem \
    -out ./certificate-https-local/cert.pem

FROM ruby:3.2.2-slim as runner

ENV RAILS_ENV=production \
    SECRET_KEY_BASE=dummy \
    RAILS_LOG_TO_STDOUT=true

RUN apt update && \
    apt install -y postgresql-client imagemagick libproj-dev proj-bin libjemalloc2 && \
    gem install bundler:2.5.22

WORKDIR /app

COPY --from=builder /usr/local/bundle /usr/local/bundle
COPY --from=builder /app /app

ENV LD_PRELOAD="libjemalloc.so.2" \
    MALLOC_CONF="background_thread:true,metadata_thp:auto,dirty_decay_ms:5000,muzzy_decay_ms:5000,narenas:2"

EXPOSE 3000
CMD ["bundle", "exec", "rails", "server", "-b", "ssl://0.0.0.0:3000?key=/app/certificate-https-local/key.pem&cert=/app/certificate-https-local/cert.pem"]